CREATE TABLE `pokemon` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pokemon` text NOT NULL,
	`type` text NOT NULL,
	`species` text NOT NULL,
	`height` text NOT NULL,
	`weight` text NOT NULL,
	`abilities` text NOT NULL,
	`ev_yield` text NOT NULL,
	`catch_rate` text NOT NULL,
	`base_friendship` text NOT NULL,
	`base_exp` text NOT NULL,
	`growth_rate` text NOT NULL,
	`egg_groups` text NOT NULL,
	`gender` text NOT NULL,
	`egg_cycles` text NOT NULL,
	`hp_base` integer NOT NULL,
	`hp_min` integer NOT NULL,
	`hp_max` integer NOT NULL,
	`attack_base` integer NOT NULL,
	`attack_min` integer NOT NULL,
	`attack_max` integer NOT NULL,
	`defense_base` integer NOT NULL,
	`defense_min` integer NOT NULL,
	`defense_max` integer NOT NULL,
	`special_attack_base` integer NOT NULL,
	`special_attack_min` integer NOT NULL,
	`special_attack_max` integer NOT NULL,
	`special_defense_base` integer NOT NULL,
	`special_defense_min` integer NOT NULL,
	`special_defense_max` integer NOT NULL,
	`speed_base` integer NOT NULL,
	`speed_min` integer NOT NULL,
	`speed_max` integer NOT NULL,
	`unnamed_32` text,
	`unnamed_33` text,
	`image` text NOT NULL,
	`index` integer NOT NULL,
	`name` text NOT NULL,
	`type1` text NOT NULL,
	`type2` text,
	`total` integer NOT NULL,
	`hp` integer NOT NULL,
	`attack` integer NOT NULL,
	`defense` integer NOT NULL,
	`sp_atk` integer NOT NULL,
	`sp_def` integer NOT NULL,
	`speed` integer NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
