import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

// Add pokemon table with all 46 columns
export const pokemon = sqliteTable('pokemon', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  pokemon: text('pokemon').notNull(),
  type: text('type').notNull(),
  species: text('species').notNull(),
  height: text('height').notNull(),
  weight: text('weight').notNull(),
  abilities: text('abilities').notNull(),
  evYield: text('ev_yield').notNull(),
  catchRate: text('catch_rate').notNull(),
  baseFriendship: text('base_friendship').notNull(),
  baseExp: text('base_exp').notNull(),
  growthRate: text('growth_rate').notNull(),
  eggGroups: text('egg_groups').notNull(),
  gender: text('gender').notNull(),
  eggCycles: text('egg_cycles').notNull(),
  hpBase: integer('hp_base').notNull(),
  hpMin: integer('hp_min').notNull(),
  hpMax: integer('hp_max').notNull(),
  attackBase: integer('attack_base').notNull(),
  attackMin: integer('attack_min').notNull(),
  attackMax: integer('attack_max').notNull(),
  defenseBase: integer('defense_base').notNull(),
  defenseMin: integer('defense_min').notNull(),
  defenseMax: integer('defense_max').notNull(),
  specialAttackBase: integer('special_attack_base').notNull(),
  specialAttackMin: integer('special_attack_min').notNull(),
  specialAttackMax: integer('special_attack_max').notNull(),
  specialDefenseBase: integer('special_defense_base').notNull(),
  specialDefenseMin: integer('special_defense_min').notNull(),
  specialDefenseMax: integer('special_defense_max').notNull(),
  speedBase: integer('speed_base').notNull(),
  speedMin: integer('speed_min').notNull(),
  speedMax: integer('speed_max').notNull(),
  unnamed32: text('unnamed_32'),
  unnamed33: text('unnamed_33'),
  image: text('image').notNull(),
  index: integer('index').notNull(),
  name: text('name').notNull(),
  type1: text('type1').notNull(),
  type2: text('type2'),
  total: integer('total').notNull(),
  hp: integer('hp').notNull(),
  attack: integer('attack').notNull(),
  defense: integer('defense').notNull(),
  spAtk: integer('sp_atk').notNull(),
  spDef: integer('sp_def').notNull(),
  speed: integer('speed').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});